jupyter_book_task:
  env:
    JULIA_NUM_THREADS: '4'
    JOBS: '4'
  auto_cancellation: true
  container:
    dockerfile: .ci/Dockerfile
    cpu: 4
    memory: 16G
  notebook_script: |
    parallel -j${JOBS} jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace {} ::: docs/*.ipynb
  build_script: |
    jupyter-book build docs --warningiserror --keep-going -v
  # Requires a PAT `GH_TOKEN` with repo scope access
  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == "main" ]]; then
  #     git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
  #     ghp-import -n -p -f docs/_build/html
  #   fi
