jupyter_book_task:
  env:
    JULIA_NUM_THREADS: auto
    JOBS: '6'
    GH_TOKEN: ENCRYPTED[!92c490aaf342b10560ad3b3f5df9f779ad4b2746df494d0803dcfcef4a5690e5c95229692b61772dfb96c007cd84eb78!]
  auto_cancellation: true
  container:
    dockerfile: .ci/Dockerfile
    cpu: 6
    memory: 24G
    use_in_memory_disk: true
  notebook_script: |
    parallel --joblog /tmp/log -j${JOBS} jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace {} ::: docs/*.ipynb
    cat /tmp/log
  build_script: |
    jupyter-book build docs --warningiserror --keep-going -v
  # Requires a `GH_TOKEN` PAT with repo scope access
  pages_script: |
    if [[ $CIRRUS_BRANCH == "main" ]]; then
      git remote set-url origin https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
      ghp-import -n -p -f docs/_build/html
    fi
