image: python:3.9-slim

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - test
  - deploy

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - jb-env/

before_script:
  - python -m venv jb-env
  - source jb-env/bin/activate
  - python -m pip install -r _jb/requirements.txt
  - jupyter-book build docs

test:
  stage: test
  except:
  - main
  script:
  - echo "Test completed."

pages:
  stage: deploy
  only:
  - main
  script:
  - mv docs/_build/html public
  - apt-get update -qq && apt-get install gzip brotli -y
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip   -f -k {} \; || echo 'Gzip failed. Skipping...'
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec brotli -f -k {} \; || echo 'Brotli failed. Skipping...'
  artifacts:
    paths:
    - public
