name: Build Binder Container

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: "ghcr.io"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install --no-cache-dir jupyter-repo2docker
    - name: Build Binder image
      run: >
        jupyter-repo2docker --no-run --user-id 1000 --user-name jovyan
        --target-repo-dir "/home/jovyan"
        --image-name ${{ env.REGISTRY }}/${{ github.repository }}:binder
        .
    - name: Login to ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image to ${{ env.REGISTRY }}
      run: docker push ${{ env.REGISTRY }}/${{ github.repository }}:binder
