name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week
  push:
    paths:
      - '.github/workflows/**'

env:
  JULIA_PKG_PRECOMPILE_AUTO: 0

jobs:
  update-notebook:
    runs-on: ['self-hosted', 'ubuntu']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Julia deps
        run: julia --color=yes --project=@. --threads=auto -e 'import Pkg; Pkg.update()'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Package Update
          token: ${{ secrets.PAT }} # PAT with repo access
          labels: |
            automerge
