name: Auto update Julia dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every week

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-manifest:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "~1.9.0-rc2"
      - name: Update Julia dependencies
        env:
          JULIA_PKG_PRECOMPILE_AUTO: 0
        run: julia --color=yes --project=@. -e "import Pkg; Pkg.update()"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          title: Julia Dependency Update
          token: ${{ secrets.PAT }}
          labels: |
            automerge
